# Generated by Django 3.2.3 on 2021-05-27 17:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Business_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_ac_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('central', 'Central'), ('local', 'Local')], max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pick_up_address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
