# Generated by Django 3.2.3 on 2021-05-27 18:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210527_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Business_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_ac_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('central', 'Central'), ('local', 'Local')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid_pic_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/nid_back/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nid_pic_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/nid_front/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pick_up_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scan_business_license',
            field=models.ImageField(blank=True, null=True, upload_to='media/business_license/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scan_check_leaf',
            field=models.ImageField(blank=True, null=True, upload_to='media/check_leaf/'),
        ),
    ]
