# Generated by Django 3.2.3 on 2021-05-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20210527_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='seller.seller'),
        ),
    ]
