# Generated by Django 3.1.7 on 2021-03-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_remove_postimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
