# Generated by Django 3.1.7 on 2021-03-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20210325_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
