# Generated by Django 3.1.7 on 2021-03-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20210325_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='size',
        ),
        migrations.CreateModel(
            name='PostSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='PostColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eshop.product')),
            ],
        ),
    ]
